[platformio]
default_envs = esp8266-d1-mini
src_dir = src
test_dir = test

[env]
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
build_flags =
  -D STAPELLS_FIRMWARE_NAME=\"base\"
  -D STAPELLS_FIRMWARE_VERSION=\"0.1.0-dev\"

[env:esp8266-d1-mini]
platform = espressif8266
board = d1_mini

[env:esp32]
platform = espressif32
board = esp32dev

[env:esp32-c3]
platform = espressif32
board = esp32-c3-devkitm-1

[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
